const DEFINE_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  ACCEPTED: "ACCEPTED",
  DENIED: "DENIED",
  CANCELED: "CANCELED",
};

const DEFINE_SCHEDULE_STATUS = {
  AVAILABLE: "AVAILABLE",
  NOT_AVAILABLE: "NOT_AVAILABLE",
};

const TRANSACTION_TYPE = {
  GATHER_BOOKING: "GATHER_BOOKING",
  COURT_BOOKING: "COURT_BOOKING",
};

export { DEFINE_STATUS, DEFINE_SCHEDULE_STATUS, TRANSACTION_TYPE };
